Make audio fetch parameters tunable
librespot-org/librespot pull request #1234
Opened 2023-12-17 17:46 UTC by lelloman

This change collects all those audio fetch parameters that were defined as static constants into a dedicated struct, AudioFetchParams. This struct can be read and set statically, allowing a user of the library to modify those parameters without the need to recompile.

2023-12-17 17:47 UTC, lelloman commented
This is to follow up on issue #1231

2023-12-20 20:21 UTC, roderickvd requested changes
Thanks! Small typo.

2023-12-20 20:21 UTC, roderickvd commented on audio/src/fetch/mod.rs
> +    pub prefertch_threshold_factor: f32,
Small typo, should be `prefetch_threshold_factor`

2023-12-24 12:10 UTC, roderickvd approved these changes

2023-12-24 12:11 UTC, merged

2023-12-24 12:11 UTC, roderickvd commented
Thanks!