Fix SpotifyId base 62 and 16 str decoding
librespot-org/librespot pull request #1239
Opened 2024-01-03 11:24 UTC by lelloman

A SpotifyId is expected to be a 128 bits integer and can be parsed from a base 62 or 16 string. However the parsing functions only checked the validity of the characters of the string, but not its length. This could result in integer overflows or the parsing of incorrect strings as Spotify ids.

This commit add some checks to the length of the input string passed to the parse functions, and also checks for integer overflows in case of base62 encoded strings.

2024-01-03 19:58 UTC, roderickvd reviewed
Thanks! One small question.

2024-01-03 19:58 UTC, roderickvd commented on core/src/spotify_id.rs
> +        if src.len() > 32 {
Should this check be ```!= 32```?

2024-03-31 09:33 UTC, roderickvd requested changes
Please check the comments on line 105.

2024-05-23 14:26 UTC, lelloman commented
I guess that https://github.com/librespot-org/librespot/pull/1284 is needed to fix the failing clippy job?

2024-05-26 20:09 UTC, roderickvd approved these changes

2024-05-26 20:09 UTC, merged

2024-05-26 20:10 UTC, roderickvd commented
Thanks! Yes the other PR is required to fix the clippy warnings.