Expose service to both IPv4 and IPv6
librespot-org/librespot pull request #1307
Opened 2024-07-16 14:47 UTC by AndersBallegaard

Change to listen to [::0] given this will make the application listen on both ipv4 and ipv6. This is useful to enable support for ipv6 only networks. 
Given most users will be on v4 only or dual stacked networks it is of course important to make sure that works, in my testing i have not found any case where this change created a problem for those devices.

2024-07-16 15:43 UTC, kingosticks commented
> in my testing i have not found any case where this change created a problem for those devices.

Just so it's clear, what patforms did you test?

2024-08-10 15:19 UTC, Frankkkkk commented
"Technically", I guess this would fail on platforms where the IPv6 stack doesn't exist (i.e. if you compile the kernel by explicitly disabling IPv6, which I guess nobody does unless you want to torture yourself). But I guess the number of people doing that is way smaller that the people that want/need IPv6 (i.e. those using NAT64, etc..)

2024-08-21 19:45 UTC, roderickvd commented
Looks good to me. Can you add an entry to the changelog? Then we can merge.

2024-08-24 15:29 UTC, willstott101 commented
This doesn't work for IPv4 on Windows :( Dual-stack sockets aren't the default.

Perhaps best to use `Ipv6Addr::UNSPECIFIED.into()` only on non-windows?

2024-08-24 21:30 UTC, Frankkkkk commented
Looks like you're right: https://github.com/rust-lang/rfcs/issues/957

That's really interesting actually

2024-08-24 23:00 UTC, roderickvd requested changes
Please refer to https://github.com/librespot-org/librespot/pull/1307#issuecomment-2308431046 and add an entry to the changelog. Thanks!

2024-08-24 23:00 UTC, roderickvd commented on discovery/src/server.rs
> +        let address = SocketAddr::new(IpAddr::from_str("::0").unwrap(), *port);
Please refer to: https://github.com/librespot-org/librespot/pull/1307#issuecomment-2308431046

2024-09-13 05:42 UTC, roderickvd commented
We're aiming for a 0.5 release next week. Would be great to get this in, if you could do the last touch-up. Thanks.

2024-10-06 20:12 UTC, roderickvd commented
Superseded by #1366

2024-10-06 20:12 UTC, closed without merging