core: audio key response timeout after 1.5s
librespot-org/librespot pull request #1360
Opened 2024-10-03 20:34 UTC by kingosticks

I spotted then when trying to track down odd behaviour in gst-plugin-spotify where things seemingly hang. I'm not sure if this was the cause because it is really hard to reproduce, but it seems like it could be a problem....?

2024-10-06 20:05 UTC, roderickvd requested changes

2024-10-06 20:05 UTC, roderickvd commented on core/src/audio_key.rs
> +        match tokio::time::timeout(Duration::from_millis(1500), rx).await {
Can you change this into a `const`?

2024-10-06 20:05 UTC, roderickvd commented
Thanks. Don't remember running into it before, but it's a good catch. Let's fix it preventively.

2024-10-07 00:17 UTC, kingosticks commented on core/src/audio_key.rs
> +        match tokio::time::timeout(Duration::from_millis(1500), rx).await {
Done

2024-10-07 05:54 UTC, merged