Add option to choose between track or album normalisation gain
librespot-org/librespot pull request #573
Opened 2021-01-21 19:13 UTC by sashahilton00

Add option to choose between track or album normalisation gain, set default normalisation gain type to album. If there's something I've missed here, let me know.

2021-01-21 19:13 UTC, sashahilton00 commented
Relevant to the conversation in #162 and closes #572

2021-01-21 19:40 UTC, sashahilton00 commented
@philippe44 if you wouldn't mind testing this, using the `--enable-volume normalisation --normalisation-gain-type track` and `--enable-volume normalisation --normalisation-gain-type album` options, that would be great, since I'm not going to be able to hear the difference through earpods to verify that it works as expected.

2021-01-21 23:02 UTC, philippe44 commented
I'm happy to help, but are you sure this message is for me? My PR does not touch/impact volume&gain normalization as it's a passthrough

2021-01-21 23:04 UTC, sashahilton00 commented
Oops, pinged the wrong person. @slartibartfast3 see above.

2021-01-21 23:54 UTC, slartibartfast3 commented
> Oops, pinged the wrong person. @slartibartfast3 see above.

I can definitely test of you tell me what I need to do. I am using Michael Herger's plugin for Squeezebox. You will easily hear the difference if you listen to the last track on Pink Floyd "The Wall". It is meant to be very low volume so using track gain is obviously far louder.

2021-01-22 15:38 UTC, slartibartfast3 commented
> 
> 
> Oops, pinged the wrong person. @slartibartfast3 see above.

Sorry it took so long but I finally managed to install everything and I can confirm it works. I used the transition between the final two tracks on "The Wall" to test it and with track gain there is a massive jump in volume whereas with album gain the tracks flow together perfectly.

2021-01-25 03:04 UTC, sashahilton00 commented
Unless there are any objections, I'll add the documentation to the wiki and merge this in a few days.

2021-01-25 19:40 UTC, herrernst requested changes
Looks good to me, thank you! Only one small issue in arguments doc, see comment.

2021-01-25 22:12 UTC, sashahilton00 commented
Yes you're right. I amended the default at the last minute and forgot to update the doc, will change that later

2021-01-27 15:16 UTC, slartibartfast3 commented
Is the label "breaking change" as serious as it sounds?

2021-01-27 15:29 UTC, ashthespy commented
> 
> 
> Is the label "breaking change" as serious as it sounds?

It depends ;-)
![image](https://user-images.githubusercontent.com/16233271/106013478-c8910f00-60bc-11eb-9ae8-8dea8a997f11.png)

https://xkcd.com/1172/

2021-01-30 02:28 UTC, sashahilton00 commented
I labelled as breaking mainly so that I have an easy reference point as to what needs to be updated in the wiki, and what needs to go into the changelog for next release.

2021-01-30 20:18 UTC, sashahilton00 commented on src/main.rs
> +            "Specify the normalisation gain type to use - [track, album]. Default is track.",
fixed.

2021-02-05 04:19 UTC, merged