Implement dithering and noise shaping
librespot-org/librespot pull request #694
Opened 2021-04-13 21:11 UTC by roderickvd

Dithering lowers digital-to-analog conversion ("requantization") error, lowering distortion and replacing it with a constant, fixed noise level, which is more pleasant to the ear than the distortion. Doing so can with a noise-shaped dither can increase the dynamic range of 96 dB CD-quality audio to a perceived 120 dB.

Guidance: experts can configure many different configurations of ditherers and noise shapers. For the rest of us, these are sane defaults depending on the output format:

Format     | Ditherer         | Noise shaper
----------|--------------|--------------
S16        | Triangular (tri) | Wannamaker (fw9 or fw24)
S24, S24_3 | High Pass (hp)   | None
S32        | None             | None
F32        | Not supported    | Not supported

Notes:

 * Try swapping ditherers with Gaussian if you prefer a more analog  sound.

 * Try swapping noise shapers with Fraction Saving if you are running  on power-constrained hardware. In this case, disable dithering.

New command-line options:

```
--dither DITHER Override the dither algorithm to use - [none, rect, sto, tri, hp, gauss].
--shape-noise SHAPE_NOISE Override the noise shaping algorithm to use - [none, fract, iew5, iew9, fw3, fw9, fw24].
```

2021-04-13 21:15 UTC, roderickvd commented
I'm pretty excited about this one, as I'm pretty certain it elevates the sound quality of `librespot` to the best in class. Please help doing some final sanity checking and code review.

2021-04-14 09:03 UTC, JasonLG1979 commented
@roderickvd this can't be configured in the vorbis decoder itself?

2021-04-14 09:48 UTC, JasonLG1979 commented
Looking at your noise shaping code you note that it basically shouldn't be used at all with delta-sigma DACs. Pretty much all DACs except niche NOS DACs are delta-sigma DACs.

I also wonder what additional noise shaping will do to the ultra-sonic part of the audio. (because noise shaping has already been applied in the mixing and mastering process)  A lot of even really expensive and otherwise objectively good DACs have horrible ultra-sonic filters. Ultra-sonic noise can damage audio equipment, especially class D amps and speakers.

2021-04-14 10:24 UTC, roderickvd commented
> @roderickvd this can't be configured in the vorbis decoder itself?

No and it shouldn't. Dithering and shaping should take place right before final requantization, after volume control, normalisation and any other filtering.

> Looking at your noise shaping code you note that it basically shouldn't be used at all with delta-sigma DACs.

That's the case for the Lipshitz and Wannamaker filters. The fraction saver works fine on delta-sigma. Thinking about this now I should turn off noise shaping by default, I'll get that done.

>Pretty much all DACs except niche NOS DACs are delta-sigma DACs.

There is quite the uprising of (quasi-) NOS multibit DACs, e.g. Schiit, Soekris, Audio-GD.

> I also wonder what additional noise shaping will do to the ultra-sonic part of the audio. (because noise shaping has already been applied in the mixing and mastering process) A lot of even really expensive and otherwise objectively good DACs have horrible ultra-sonic filters. Ultra-sonic noise can damage audio equipment, especially class D amps and speakers.

Well as you point out, it's the DAC's job to filter above Nyquist. Usually if filters are "bad", they have an early roll-off or cause modulation distortion. It's something else entirely if they fail to roll-off above Nyquist and leave ultrasonic noise intact! That's just broken. Also properly designed, non-DIY-modded DACs will have an output capacitor for low pass filtering _in hardware_ even if the filter software is of poor design.

I think when you refer to poor filters, you are more referring to the first case of poor sound quality, rather than broken and potentially destructive behavior. Of course we can only assume the DAC is of a safe design.

2021-04-14 10:35 UTC, coderootme commented
> New command-line options:
> 
> ```
> --dither DITHER Override the dither algorithm to use - [none, rect, sto, tri, hp, gauss].
> --shape-noise SHAPE_NOISE Override the noise shaping algorithm to use - [none, fract, iew5, iew9, fw3, fw9, fw24].
> ```
> 

Can the description state what is the default option, i.e. what happens when we don't specify these parameters?

2021-04-14 11:00 UTC, JasonLG1979 commented
> I think when you refer to poor filters, you are more referring to the first case of poor sound quality, rather than broken and potentially destructive behavior. Of course we can only assume the DAC is of a safe design.

Have you ever checked out https://www.audiosciencereview.com/ they do A LOT of objective DAC measurements. From their measurements it's way more likely that a DAC doesn't roll off enough ultra-sonics then too much. If assumptions are to be made I would assume a poor DAC implementation over an ideal one.

2021-04-14 11:11 UTC, JasonLG1979 commented
> There is quite the uprising of (quasi-) NOS multibit DACs, e.g. Schiit, Soekris, Audio-GD.

Those are still very niche in the grand scheme of things. 99.99% of DACs out there are delta-sigma DACs. In fact most of the chips are made by just 3 manufacturers, ESS, AKM and TI and those are all delta-sigma DACs.

2021-04-14 11:26 UTC, JasonLG1979 commented
I'm just a little weary of a feature that could damage someone's hardware, even if the chance is less than microscopic. At the very least I think the noise shaping noise should be limited in spectrum to 20kHz, if it isn't already, to at least not add any ultra-sonics on it's own.

I'm somewhat talking out of my butt here so don't take anything I say as we trying to say I actually know what I'm talking about,lol!!! If you know better you know better. Just giving you some things to think about. Basically any statement I make could also be heard as a question.

2021-04-14 11:31 UTC, JasonLG1979 commented
> No and it shouldn't. Dithering and shaping should take place right before final requantization, after volume control, normalisation and any other filtering.

But it does happen during mixing, mastering and the decoding of lossy audio.

2021-04-14 11:38 UTC, Johannesd3 commented
I'm sure you're doing a great job, but I'm not sure this is the appropriate place for such a sophisticated sound processing. As far as I understood, dithering and noise shaping are some kind of filters which take PCM, modify it, and return new PCM. Unlike volume normalization or volume control, they don't have to interact with the Spotify backend, but are statically applied, using parameters set at the start of the program. Please correct me if I'm wrong.

I also think this adds a lot of complexity to the code. Every backend was modified to implement something rather specific. One could even imagine that more kinds of filters are added to librespot, and it's not really nice to touch every backend every time, using only "macro magic" to abstract over it.

If there would be at least some more general approach, for example to create pipelines of filters, so you can modify the processing without changing all backends. But IIUC this would be very close to what gstreamer does. And maybe too much for a simple Spotify player.

Most people won't hear any difference, so it's IMO not necessary to support it out of the box. If someone really needs this, they could also invest some time in an advanced audio setup, e.g. piping the audio into some application that supports this.

2021-04-14 11:45 UTC, roderickvd commented
> > I think when you refer to poor filters, you are more referring to the first case of poor sound quality, rather than broken and potentially destructive behavior. Of course we can only assume the DAC is of a safe design.
> 
> Have you ever checked out https://www.audiosciencereview.com/ they do A LOT of objective DAC measurements. From their measurements it's way more likely that a DAC doesn't roll off enough ultra-sonics then too much. If assumptions are to be made I would assume a poor DAC implementation over an ideal one.

Sure. As a recent example, Amir even strongly recommended one DAC that has noise shaping above 45 kHz: https://www.audiosciencereview.com/forum/index.php?threads/topping-d30pro-review-balanced-dac.20259/
Ultrasonic noise on class D becomes an issue around the switching frequency of the amplifier which is often between 200 kHz and 2 MHz.

Picking another topic off of ASR on this subject: https://www.audiosciencereview.com/forum/index.php?threads/how-does-ultrasonic-noise-affect-the-sound-quality.11558/ So while it's good that you brought this up, I think it's safe to say that we're in the green here.

Anyway, noise shaping is now off by default as of 6ea089c, which I agree with.

> > No and it shouldn't. Dithering and shaping should take place right before final requantization, after volume control, normalisation and any other filtering.
> 
> But it does happen during mixing, mastering and the decoding of lossy audio.

I'm not sure what you are arriving at. Yes, there is or should be dithering during mixing and mastering analog-to-digital (quantization). This does not waive dithering when going back again from digital-to-analog (requantization).

There is no dithering or `libvorbis` or `lewton` and earlier I explained why. And if you don't dither during requantization, you will have greater audible noise then when you would have dithered.

I don't think I need to expound here why dithering or not is a useful feature, please refer to the seminal and publicly available academic works of Lipshitz and Wannamaker, books  or even Wikipedia.

2021-04-14 11:56 UTC, JasonLG1979 commented
@roderickvd calm down,lol!!!

Like I said if you know you know. I was just trying to wrap my brain around what you're doing here. As I've said I was semi talking out my butt. I agree with the benefit of dithering and noise shaping especially when used with software volume and gain leveling I'm just wondering now if there really needs to be options beyond what works (safely) for resource constrained devices and what works for everything else like maybe just a "good" and "better" option that defaults to "good".

2021-04-14 11:57 UTC, roderickvd commented
> I'm sure you're doing a great job, but I'm not sure this is the appropriate place for such a sophisticated sound processing. As far as I understood, dithering and noise shaping are some kind of filters which take PCM, modify it, and return new PCM. Unlike volume normalization or volume control, they don't have to interact with the Spotify backend, but are statically applied, using parameters set at the start of the program. Please correct me if I'm wrong.

This is correct. In the context of #648 this is a direct candidate for moving into a separate crate or daemon, which I'm in full support of but that's not today.
 
> I also think this adds a lot of complexity to the code. Every backend was modified to implement something rather specific. One could even imagine that more kinds of filters are added to librespot, and it's not really nice to touch every backend every time, using only "macro magic" to abstract over it.

That's exactly why I propose the `Requantizer` class, which encapsulates all current and future behavior. Add this API now and be done with it for the future.

> Most people won't hear any difference, so it's IMO not necessary to support it out of the box. If someone really needs this, they could also invest some time in an advanced audio setup, e.g. piping the audio into some application that supports this.

I say that as long as there is audio playback in librespot, we should make it the best we can, then move it out later.

2021-04-14 12:01 UTC, roderickvd commented
> @roderickvd calm down,lol!!!

No worries mate. May I still bother you for performance testing on your RPi Zero?

2021-04-14 12:06 UTC, JasonLG1979 commented
> No worries mate. May I still bother you for performance testing on your RPi Zero?

For sure. Absolutely. I will test it out later today or tonight.

And let me say as an audio enthusiast on a budget I thank you for doing what you can to make librespot sound as good as it can. I can't wait for your work to filter down us raspotify users.

2021-04-14 12:09 UTC, JasonLG1979 commented
Speaking of the Pi Zero is that our potato now? Because the librespot devs really need to officially pick a potato.

( potato = lowest spec target device )

2021-04-14 13:13 UTC, roderickvd commented
> > New command-line options:
> > ```
> > --dither DITHER Override the dither algorithm to use - [none, rect, sto, tri, hp, gauss].
> > --shape-noise SHAPE_NOISE Override the noise shaping algorithm to use - [none, fract, iew5, iew9, fw3, fw9, fw24].
> > ```
> 
> Can the description state what is the default option, i.e. what happens when we don't specify these parameters?

Added in 00b36be.

2021-04-14 13:17 UTC, coderootme commented
> > > New command-line options:
> > > ```
> > > --dither DITHER Override the dither algorithm to use - [none, rect, sto, tri, hp, gauss].
> > > --shape-noise SHAPE_NOISE Override the noise shaping algorithm to use - [none, fract, iew5, iew9, fw3, fw9, fw24].
> > > ```
> > 
> > 
> > Can the description state what is the default option, i.e. what happens when we don't specify these parameters?
> 
> Added in [00b36be](https://github.com/librespot-org/librespot/commit/00b36be390c5f30edda56334b771f2995c8bde0a).

Thank you!

Maybe for future reference, could you please tell us why dithering is not supported for `F32` and `S32`, i.e. does it mean that for these modes dithering is not required, i.e. these modes are the most transparent of all?

2021-04-14 13:32 UTC, roderickvd commented
> Maybe for future reference, could you please tell us why dithering is not supported for `F32` and `S32`, i.e. does it mean that for these modes dithering is not required, i.e. these modes are the most transparent of all?

Dithering is supported, but completely unnecessary on `S32` because any quantization noise is so far down the noise floor, that both the noise itself and any modulation distortion is next to zero. Simply inaudible.

Dithering on `F32` makes no sense because floats more or less represent a continuous-valued signal and so have no quantization noise resulting from rounding to integer values.

There is one case that I should document, which is the case where your backend supports `F32` or `S32` but your hardware doesn't, and the backend converts down without dithering. In that case convert down in librespot, not in the backend. Example: my DAC supports up to `S24` audio over I2S, and Alsa accepts up to `F32`. Alsa would convert down without dithering, so I run `librespot` with `--format S24 --dither hp` for optimal sound quality.

2021-04-14 16:41 UTC, JasonLG1979 commented
> Alsa accepts up to `F32`. Alsa would convert down without dithering

If you run though dmix. If you directly address your DAC trying to give it a format or sampling rate it doesn't support it will just fail. Dmix by default resamples/converts everything to 16 bit 48 khz. 

You can use `aplay -l` to find your card. and something like `aplay -Dhw:0,0 --dump-hw-params /usr/share/sounds/alsa/Front_Right.wav` (replacing `0:0` with the card # and device #) to tell what sampling rates and formats your DAC actually supports.

You'll see something that looks like `FORMAT:  S16_LE S24_LE S32_LE` and `RATE: [8000 192000]`.

For the best quality as far as format is concerned I'd either configure dmix to the highest supported format if you need software mixing or just address the card directly if you don't and skip dmix. Either way you'd want to configure librespot to that same highest supported format.

As far as the sampling rate goes if you run though dmix you'd also want to make sure that's it's 44100 to match what librespot outputs unless you want your audio resampled for whatever reason. Resampling has questionable benefit and can be expensive CPU wise.

2021-04-15 14:44 UTC, Johannesd3 commented on audio/src/dither.rs
> +    fn name(&self) -> String;
Why not use `&'static str` instead of `String`?

2021-04-15 14:44 UTC, Johannesd3 commented on audio/src/shape_noise.rs
> +                format!("{}, {} taps", $description, Self::WEIGHTS.len())
Here you could use the `concat!` and `stringify!` macros.

2021-04-15 14:44 UTC, Johannesd3 commented on examples/play.rs
> +    let noise_shaper = shape_noise::find_noise_shaper(None).unwrap();
Anyone who would see this example to implement their own simple player would get confused, I believe. Is it really necessary to give them such a prominent place in the API?

2021-04-15 15:33 UTC, JasonLG1979 commented
@roderickvd Sorry I'm a little late. I'm building your branch right now on my Pi Zero with the `--release --no-default-features --features "alsa-backend"` compile flags the resulting binary should, if all goes well,  be `arm-unknown-linux-gnueabihf` compatible so basically it should tun on at least any Raspberry Pi running a 32 bit version of Raspberry Pi OS. (and a few other small ARM boards?) if anyone would also like to test the build but doesn't want to compile it, let me know and I'll post the binary somewhere for you to download.

I'll unscientifically test a few different config options to get a ballpark of performance (basically how bad does it hurt the Pi Zero's CPU) compared to the current stable branch.

2021-04-15 20:03 UTC, Johannesd3 requested changes

2021-04-15 20:03 UTC, Johannesd3 commented on audio/src/shape_noise.rs
> +                concat!($description, ", ", stringify!(Self::WEIGHTS.len()), " taps")
Don't think this works. Try this, but I'm not sure:
```suggestion
                concat!($description, ", ", stringify!($taps), " taps")
```

2021-04-15 20:47 UTC, Johannesd3 submitted a review, later dismissed

2021-04-15 20:50 UTC, Johannesd3 commented
... no, I didn't want to say that I agree with everything. I don't understand GitHub properly.

2021-04-15 21:03 UTC, Johannesd3 commented on examples/play.rs
> +    let noise_shaper = shape_noise::find_noise_shaper(None).unwrap();
To be clear, I think `PlayerConfig` would be a more appropriate place to configure things like this.

2021-04-16 20:46 UTC, JasonLG1979 commented
@roderickvd Even trying to hurt the CPU with `--format S24 --dither tri --shape-noise fw24` it only hits 50% ish during normal playback on my Pi Zero running at the stock clock speeds. And if I omit `--shape-noise fw24` it goes down to 30% ish. With `--format S32` with not dithering and noise shaping by default it's around 20% ish. I'd call that a win.

2021-04-20 08:47 UTC, Johannesd3 commented
I don't understand everything, but what exactly prevents us from applying the `Requantizer` before `Sink::write`, i.e. still in the player? Is it because it has to take place after converting the samples? If so, I would actually prefer a solution where conversion takes place before it is put into the sink.

How about something like this: Make `Sink` generic over the audio format (by introducing a `Sample` trait), and then make a struct (I'm too lazy to think about names) `Foo<F: Sample, S: Sink<F>>` which converts `f32` to `F` and applies dithering and noise shaping. Create a trait `Bar` (non-generic) which resembles the current `Sink` trait, i.e it takes `f32` samples, and implement it for `Foo`. Use `Box<dyn Bar>` instead of  `Box<dyn Sink>` in the player.

It's just a rough idea, I don't know if it would work out. What do you think of it?

2021-04-20 10:20 UTC, roderickvd commented
> I don't understand everything, but what exactly prevents us from applying the `Requantizer` before `Sink::write`, i.e. still in the player? Is it because it has to take place after converting the samples?

Yes, that's correct, when the `[-1.0; 1.0]` PCM representation in `f32` is "promoted" to `[std::T::MIN; std::T::MAX]` integer value but *before* casting to actual integer type `T` so that we can work with the fraction. (An oversimplified but hopefully illustrative explanation of dithering is that we linearize the output by randomly rounding the input up or down.)

> If so, I would actually prefer a solution where conversion takes place before it is put into the sink.

Semantically I see your point that a `Sink` should just sink and not do any processing.

> How about something like this: Make `Sink` generic over the audio format (by introducing a `Sample` trait), and then make a struct (I'm too lazy to think about names) `Foo<F: Sample, S: Sink<F>>` which converts `f32` to `F` and applies dithering and noise shaping. Create a trait `Bar` (non-generic) which resembles the current `Sink` trait, i.e it takes `f32` samples, and implement it for `Foo`. Use `Box<dyn Bar>` instead of `Box<dyn Sink>` in the player. (Edit: Or instead of `Bar` use `Sink<f32>`, with hardcoded generic argument)

More insighftul naming would help me wrap my head around this. If I understand correctly `Foo` would be something like an `AudioRenderer` or perhaps the `Requantizer` in new form? With something like `audio_renderer.from(packet: &AudioPacket)` with `AudioPacket` always in `&[f32]`? Then what is the purpose of `Bar`?

> It's just a rough idea, I don't know if it would work out. What do you think of it?

I don't know, I think it would be a lot of work in the backends. I don't think you can dynamically infer what type `T` is so for many backends it would require chopping them up in their `f32`, `i32`,  `i24` and `i16` counterparts, adding a lot of lines with quite some duplication. Macros would help DRYing some of that up but at the cost of code complexity.

For `i32` there is the additional complexity that you can't infer if `i32` samples are  `S32` or `S24` (`i24` is actually `S24_3`).

Also I think it would move up output format from the backend, to the player, which is not really its concern (also the backend needs to know when opening the device). So basically I think it would require rewriting much of what was in #660 or am I misunderstanding?

Coming back to the start, semantically I think I understand where you're coming from but would this be worth the trouble?

If the point is semantics, an alternative would be to just rename `Sink` to the likes of `AudioRenderer` and renaming the current `write` to `render` to better state the intention. This PR then already processes the samples before *actually* sinking them to the *real* backend (e.g. Rodio, Alsa, ...) So I think the behavior you describe is already there but under different naming.

Thanks for your review and thoughts, I appreciate it.

2021-04-20 11:34 UTC, Johannesd3 commented
> So basically I think it would require rewriting much of what was in #660

Yes.

> or am I misunderstanding?

No.

Please take a look at this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2ad7ac7b41ec531b26bd32d6af2dffa8

If you and @sashahilton00 appreciate this idea, I would suggest postponing this PR, deciding about #692, then implementing this suggestion, but without `Requantizer`. After this, implementing dithering and noise shaping would be much less invasive.

2021-04-20 12:48 UTC, roderickvd commented
> If you and @sashahilton00 appreciate this idea, I would suggest postponing this PR, deciding about #692, then implementing this suggestion, but without `Requantizer`. After this, implementing dithering and noise shaping would be much less invasive.

I'm in favor of doing #692 regardless, it's good plumbing. Would be nice if that could get merged in short time so we can go on with future work without major merging conflicts.
 
> Please take a look at this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8141f88cfcf99f03676903cd52b359d6
>
> P.S.: ~I'm still looking for a good way to create the Sinks for the individual backends without specialization which is not (yet) supported in Rust.~
>
> Maybe something like this:
> 
> Make this function available to all backends:
> 
> ```rust
> fn apply_filters<S: Sink>(sink: S) -> Box<dyn Sink<Sample=f32>> { 
>      Box::new(SampleConverter::new(Requantizer::new(sink)))
> } 
> ```
> 
> And a backend-specific implementation could roughly look like:
> 
> ```rust
> trait SupportedAlsaSample: Sample {
> 	fn get_format() -> alsa::Format;
> }
> 
> struct AlsaSink<S: SupportedAlsaSample> {
> 	// ...
> }
> 
> impl<S: SupportedAlsaSample> Sink for AlsaSink<S> {
> 	type Sample = S;
> 	// ...
> }
> 
> fn open_alsa(format: AudioFormat) -> Box<dyn Sink<Sample=f32>> {
> 	match format {
> 		S16 => apply_filters(AlsaSink::<i16>::new())
> 		F32 => apply_filters(AlsaSink::<f32>::new())
> 		// ...
> 	}
> }
> ```

Yes, specialization or overloading would make life easier. Your Rust is better than mine, I'm still learning. With that in mind I think your proposal is cleaner OOP-wise, but to me is harder to read (reminds me of Rodio which tries to make things transparent, but consequently also a bit magical). But if this is the route @sashahilton00 and you want to take, then I'm sure I'll be able to follow.

Questions if we were to go that route:
 1. How to deal with `S24`? (which is in `i32` but unlike `S32`, only 24 bits of data MSB padded with 8 bits)
 2. There's one more instance of filtering: volume control by the mixer. Best to also take this in here?

https://github.com/librespot-org/librespot/blob/7226bfd55ab72fb3d35a35f3bc38582975a8bec1/playback/src/mixer/mod.rs#L9-L11

2021-04-20 13:03 UTC, Johannesd3 commented
> With that in mind I think your proposal is cleaner OOP-wise, but to me is harder to read (reminds me of Rodio which tries to make things transparent, but consequently also a bit magical).

You're mostly using macros to avoid repetion, which I find unreadable in return. But I think it's a matter of taste. I wrote this draft in 10 minutes, so maybe there are some possibilities to improve clarity.

>   1. How to deal with `S24`? (which is in `i32` but unlike `S32`, only 24 bits of data MSB padded with 8 bits)

2 variants:
* New type wrapper: `struct i24_4(pub i32)`
* `trait AudioFormat { type Sample: Copy + Send; fn from_f32(_: &f32) -> Self::Sample; }` and `struct S24;`, `struct F32;` and so on.

> There's one more instance of filtering: volume control by the mixer. Best to also take this in here?

I'm not familiar with the mixer, but if it works, why not?

*** 

One thing I'm not sure about is configuration. My proposal needs the config of dithering & co while creating the sink, so your latest modification to simplify the examples would not work here. Maybe the way to go is:
```rust
#[derive(Default)]
struct SinkConfig {
    pub device_id: Option<String>,
    pub audio_format: AudioFormat,
    /* ...noise shaping and dithering stuff... */
}

fn apply_filters<S: Sink>(sink: S, config: SinkConfig) -> Box<dyn Sink<Sample = f32>> { 
```

2021-04-20 19:52 UTC, roderickvd commented
> You're mostly using macros to avoid repetion, which I find unreadable in return. But I think it's a matter of taste. I wrote this draft in 10 minutes, so maybe there are some possibilities to improve clarity.

I certainly do love DSL's 😄 
 
> > 1. How to deal with `S24`? (which is in `i32` but unlike `S32`, only 24 bits of data MSB padded with 8 bits)
> 
> Two options:
> 
> * New type wrapper: `struct i24_4(pub i32)`
> * `trait AudioFormat { type Sample: Copy + Send; fn from_f32(_: &f32) -> Self::Sample; }` instead of `trait Sample`, and unit structs `S24`, `F32` and so on, which implement `AudioFormat`.
> 
> ~I would prefer the first option.~ I think the second option could solve some other difficulties of this approach. We need to investigate this further.

Perhaps settling on good naming will be helpful. Here, an `AudioFormat` is kind of convoluted as a "format" generally sounds like an enum, not something that has behaviour. I like your earlier gist, I think it helps mapping out an API.

> > There's one more instance of filtering: volume control by the mixer. Best to also take this in here?
> 
> I'm not familiar with the mixer, but if it works, why not?

Just to be sure, do you mean to leave it be, or to likewise  make it into a `Sink` (new nomenclature)?

Only place it's used, and likely will ever be, is in `softmixer`. Alsa doesn't require it nor will `alsasoftvol` that I'm considering adding in #685.

https://github.com/librespot-org/librespot/blob/7226bfd55ab72fb3d35a35f3bc38582975a8bec1/playback/src/mixer/softmixer.rs#L37-L47

Thinking out loud, even the normalisers could be candidates for `Sink` implementations. They are all filters of some kind. Again is it worth the trouble?

> One thing I'm not sure about is configuration. My proposal needs the config of dithering & co while creating the sink, so your latest modification to simplify the examples would not work here.

Which, as you pointed out during your earlier review, also increases coupling between dithering et al and the backend, which should ideally not care if it's getting dithered samples or not. But one way or the other there will be coupling. My first proposal was to `Sink::open`. My second proposal was to `Sink::write`. Your proposal is likewise to `Sink::write` but adding a generic `Sample` pipeline. Which is the lesser of evils?

2021-04-20 20:57 UTC, Johannesd3 commented
I extended my example a little bit: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=35220c20100809a959e81cf79f0d0a60


> Perhaps settling on good naming will be helpful. Here, an AudioFormat is kind of convoluted as a "format" generally sounds like an enum, not something that has behaviour.

Maybe that's because you're used to the fact that `AudioFormat` is an enum? However, as shown in the above playground link, both an enum and a trait are necessary to describe audio formats, so I agree, we need  better naming.

> Thinking out loud, even the normalisers could be candidates for Sink implementations. They are all filters of some kind. Again is it worth the trouble?

That's a question we can think later about.

> Which, as you pointed out during your earlier review, also increases coupling between dithering et al and the backend, which should ideally not care if it's getting dithered samples or not. But one way or the other there will be coupling. My first proposal was to Sink::open. My second proposal was to Sink::write. Your proposal is likewise to Sink::write but adding a generic Sample pipeline. Which is the lesser of evils?

I think my solution is not bad, there is a struct `SinkConfig` which is passed to a backend-specific `fn open`. This functions uses only a few fields, but passes the struct to a shared function `apply_filters<S>`. So we can modify most fields of `SinkConfig` without touching the backends.

2021-04-20 21:07 UTC, Johannesd3 commented
@roderickvd Would you like to create a repository where we can experiment with this idea independently from librespot? (or should I create it?) I really could imagine this part as its own crate.

2021-04-21 08:37 UTC, Johannesd3 commented
I created a repository called [sinky](https://github.com/Johannesd3/sinky) where I'd like to experiment with this idea. (I've chosen this name because the main trait is `Sink`. Does it sound ok even for native english speakers?) You are invited to give feedback or to create PRs.

2021-04-21 09:07 UTC, roderickvd commented
> I extended my example a little bit: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=35220c20100809a959e81cf79f0d0a60

That's great, I'll look into it later when I have more time (also your `sinky` repository).
 
> @roderickvd Would you like to create a repository where we can experiment with this idea independently from librespot? (or should I create it?) I really could imagine this part as its own crate.

What I'd really like is for the maintainers to wrap up on the growing list of PR's (some of which trivial, some fixes for regressions, others to be decided on), get a new release out of the door, thereby establishing a new baseline. Then collaborate on `sinky` as The Next Big Thing.

For this specific PR I too ask to merge now, then refactor later as part of `sinky`. It's working fine under the current architecture (this discussion might make it seem otherwise).

2021-04-21 11:53 UTC, kingosticks commented
> I've chosen this name because the main trait is Sink. Does it sound ok even for native english speakers?

I'm not properly following what this stuff is doing but in things like Pulseaudio and GStreamer, normally sinks are considered endpoints that consume data i.e they have an input but not an output. For things that modify data: like dithering, volume control, noise shaping, etc - don't these all have both an input and and output? I'm not saying Gstreamer has this correct, but in that ecosystem they would be called [filters](https://gstreamer.freedesktop.org/documentation/application-development/basics/elements.html?gi-language=c#filters-convertors-demuxers-muxers-and-codecs) and I think that's similarly true in other audio applications. Apologies if I've got the wrong end of the stick here...

2021-04-21 12:03 UTC, Johannesd3 commented
> > I've chosen this name because the main trait is Sink. Does it sound ok even for native english speakers?
> 
> I'm not properly following what this stuff is doing but in things like Pulseaudio and GStreamer, normally sinks are considered endpoints that consume data i.e they have an input but not an output. For things that modify data: like dithering, volume control, noise shaping, etc - don't these all have both an input and and output? I'm not saying Gstreamer has this correct, but in that ecosystem they would be called [filters](https://gstreamer.freedesktop.org/documentation/application-development/basics/elements.html?gi-language=c#filters-convertors-demuxers-muxers-and-codecs) and I think that's similarly true in other audio applications. Apologies if I've got the wrong end of the stick here...

The idea is that sink + filter is again a sink. Like iterator + map is again an iterator.

We could also create a trait `Filter`, and a struct `FilteredSink<F: Filter, S: Sink>` which applies the filter and forwards it into the sink. But this struct could again be interpreted as `Sink`, because it takes audio and outputs it. But I don't think this struct is necessary, manually implementing `Sink` is good enough.

2021-04-28 10:27 UTC, Johannesd3 approved these changes
Ok, if this feature is wanted, this is IMO the best way to implement it without doing much refactoring.

2021-04-28 10:27 UTC, Johannesd3 commented on audio/src/convert.rs
> +    }
I think the `Ditherer` and `NoiseShaper` traits should have default functions that take buffers of samples and modify them, and shaped_dither should take buffers itself and call these functions instead to reduce the number of dynamically dispatched function calls. (On the other hand, there seems not to be a performance problem, so it's not that important)

2021-04-30 17:21 UTC, roderickvd commented
There's a code optimisation plus fix for 24-bit output I want to get out first.

2021-05-01 00:14 UTC, sashahilton00 commented
Can one of the other maintainers or equally anyone else with experience of this chime in here as to whether we think we want this in the library? I'm not experienced enough in audio to be able to review the logic behind this commit, and my ears aren't good enough to tell the difference, at least not with laptop speakers. As such ideally @roderickvd would commit to maintaining/refining this functionality in the future if this is to be considered for addition, as otherwise it could end up just being an unknown/unmaintainable chunk for future contributors.

2021-05-01 07:48 UTC, Johannesd3 commented
In general, my opinion from https://github.com/librespot-org/librespot/pull/694#issuecomment-819451765 remains. I would postpone such elaborate audio processing until there is a more modular solution, because it's not urgent: I'm pretty sure there are alternative solutions using the pipe backend or so, and most people won't hear a big difference, so there's no need to work out of the box.

However, if _you_ still want it (it doesn't seem so), I'm convinced it's the best way to implement it without refactoring the sinks heavily.

2021-05-01 10:01 UTC, roderickvd commented
I really found a new hobby contributing to this project, so don't expect me to leave anytime soon unless you want me to 😆 I'm in here for the long haul, not to scratch an itch and wave goodbye.

Naturally I'm biased so it'd be great to hear some more opinions. Even on low quality hardware and without golden ears, dithering is likely to decrease listening fatigue. So I'm hoping to bring this to the masses and make `librespot` output the best it can be.

2021-05-10 01:50 UTC, JasonLG1979 commented
> Can one of the other maintainers or equally anyone else with experience of this chime in here as to whether we think we want this in the library? I'm not experienced enough in audio to be able to review the logic behind this commit, and my ears aren't good enough to tell the difference, at least not with laptop speakers.

Not that I'm an expert on audio processing or library management but in general dithering and noise shaping is pretty standard and from what I can tell is the "right" way to do things. If my opinion is worth anything I would say that like it or not librespot does playback. It may as well be done right. With that in mind my vote (if I had one) would be to include this and move all playback stuff to a separate crate in whichever order makes the sense.

So far in just a couple commits @roderickvd is taking librespot from "well, it makes noise?" to "Wow, this actually sounds really good, all things considered." I'm an objectivist audio enthusiast. I can honestly say that so far what he has proposed are objective improvements that add value to librespot.

2021-05-16 21:57 UTC, JasonLG1979 commented
@roderickvd is this ready to test?

2021-05-16 22:02 UTC, roderickvd commented
It is. This last commit is really just moving it from `audio` to `playback`. It worked well before, but it’s good to put it through its paces again.

2021-05-17 04:21 UTC, JasonLG1979 commented
@roderickvd everything still looks good, as expected.

We will definitely need to get together on a wiki page that does a deep dive into audio configuration after this and the volume PR gets merged. It would be worth it to demystify some of the librespot args and audio configuration in general. I can help with ALSA but I know nothing about Windows nor MacOS. I think a good wiki page or 2 can really cut down on the "How do I do this?" type bug reports and in general help people get the most use out of librespot.

2021-05-17 12:59 UTC, roderickvd commented
Sure thing. I intentionally added quite a bit of comments in the code, that could easily be used. For the most part I don't think the operating system matters much. Great if you would help out with this. 

For now I think the jury is still out on this PR -- how may I help to reach a verdict? I feel like the root of the hesistance comes from indecision whether we want playback in `librespot` or really just make it a library. Why make this a XOR decision when we can have the best of both worlds?

2021-05-17 15:02 UTC, JasonLG1979 commented
> Sure thing. I intentionally added quite a bit of comments in the code, that could easily be used. For the most part I don't think the operating system matters much. Great if you would help out with this.

For the most part for average users the OS really shouldn't matter but for Linux at least, especially in the case of a dedicated device there are tweaks and tricks to get the most out of your device and librespot that a person that's new to Linux would not know like setting up ALSA softvol or figuring out what formats their DAC supports for example. 

> For now I think the jury is still out on this PR -- how may I help to reach a verdict? I feel like the root of the hesistance comes from indecision whether we want playback in `librespot` or really just make it a library. Why make this a XOR decision when we can have the best of both worlds?

IMHO like it or not librespot already does playback, that bridge has been crossed. It might as well be the best it can be. If everything is broke out into separate crates it can already be used as a pure lib without playback right?

2021-05-18 18:17 UTC, herrernst commented
While I very much appreciate your effort, I also doubt the librespot is the best place to implement dithering and noise shaping. I think it better belongs to rodio or cpal, maybe as a library/plugin/crate. I think librespot shouldn't get too bloated to become unmaintainable at some point.

2021-05-18 19:59 UTC, roderickvd commented
I dislike the `cpal` and `rodio` architectures and do not intend to actively contribute to those projects. They also rob users of opportunities for high quality audio in 99% of cases. See my comment at https://github.com/librespot-org/librespot/issues/727#issuecomment-842570178.

While I respect all perspectives, I'd like to avoid FUD. With all of this living in the `playback` crate, first of all `librespot` crates can easily be used without any playback at all. Second, I already stated I'm willing to maintain my contributions and think I have shown that with more than words. Third, failing all else, it's easy to take out. It would even be easy to feature gate it as is.

2021-05-18 20:04 UTC, herrernst commented
> I dislike the `cpal` and `rodio` architectures and do not intend to actively contribute to those projects. They also rob users of opportunities for high quality audio in 99% of cases. See my comment at [#727 (comment)](https://github.com/librespot-org/librespot/issues/727#issuecomment-842570178).

Okay, understood. But still, wouldn't it then be more appropriate to do noise shaping in a gstreamer or alsa plugin then?

> While I respect all perspectives, I'd like to avoid FUD. With all of this living in the `playback` crate, first of all `librespot` crates can easily be used without any playback at all. Second, I already stated I'm willing to maintain my contributions and think I have shown that with more than words. Third, failing all else, it's easy to take out. It would even be easy to feature gate it as is.

Okay, you have won me over  😀

2021-05-18 20:46 UTC, roderickvd commented
It's true that GStreamer can do dithering and noise shaping and has good cross-platform support. In fact it will dither by default if it is fed `F32` samples (which is not the default). Alsa doesn't do any dithering and likely never will for reasons of supporting all Linux targets, and so doing conversions in integer instead of float.

Doing this here makes dithering available to all backends and completely transparent for the user. No fiddling with backend plugins or thinking how to make `--format F32` work with your hardware that likely won't support `F32`. Ironically, it are the default cases of `--format S16` and `--backend rodio` that profit the most, and where we'd look after users not so skilled in technical audio matters (which does not mean they won't appreciate high quality playback or even have high quality hardware).

As I said before, as long as there's playback in `librespot`, let's make it the best it can be.
Especially with support for various direct backends.

2021-05-18 21:25 UTC, JasonLG1979 commented
> As I said before, as long as there's playback in `librespot`, let's make it the best it can be.
> Especially with support for various direct backends.

Pros:

It improves sound quality for everyone even if you don't want to deep dive and tweak things.
It's the bog-standard "right" thing to do from an audio processing standpoint in conjunction with software volume control and normalization. 
It's easy to not use it if you want to use` librespot` more as a lib.

Cons:

The defaults seem sensible, which is the most important part but with so many different combos of dithering and noise shaping and considering that in my testing even the most computationally heavy setting will run on a Pi Zero no problem, I wonder if logical combos can't be a little more abstracted out basically something like just a setting for delta-sigma DACs (which seems to already be the default) and a setting or settings specifically for NOS/R2R/multi-bit Dacs?

2021-05-18 22:12 UTC, Johannesd3 commented
I suggested already a design which would allow moving audio processing into a separate crate and separate filters. Maybe it's really more appropriate to introduce such a design first.

2021-05-18 23:22 UTC, JasonLG1979 commented
> I suggested already a design which would allow moving audio processing into a separate crate and separate filters. Maybe it's really more appropriate to introduce such a design first.

Dithering and noise shaping aren't really "effects". They are standard things done as a part of software volume control, normalization and generally even decoding lossy audio formats to mitigate distortion/noise caused by quantization errors. They are generally best thought of as reconstruction filters, kinda, but not really like a physical low-pass filter on a Class D amp's output in the sense of, could you build a class D amp without a low-pass'd output? Sure, but why would you if including the filter is the right way to do it and it sounds better.

IMHO playback is exactly the right place for them to be.

2021-05-19 06:51 UTC, Johannesd3 commented
> Dithering and noise shaping aren't really "effects". They are standard things done as a part of software volume control, normalization and generally even decoding lossy audio formats to mitigate distortion/noise caused by quantization errors.

It doesn't change that it's a huge chunk of code that none of the maintainer really understands. 

You two are probably living in your hi-fi bubble, and dithering and noise shaping are an important thing to you. But I have never heard of it before, I've never used an audio player which had a setting with this name, and I honestly didn't miss it. The only one of the backends that would support it out of the box would be gstreamer, wouldn't it?

It just doesn't mean anything to "ordinary" people. I'd just be glad to deliver the audio as close as possible to the original, maybe even bit perfect, and if someone isn't satisfied, they could do whatever they want with it, but just after librespot. 

And believe it or believe it not, but outside of your bubble no one would hear a difference. 

That is why I'm not really convinced that the change is worth the additional code complexity, the close integration into every single backend and all the configuration option that most users won't understand are worth it.

2021-05-19 07:14 UTC, JasonLG1979 commented
> It doesn't change that it's a huge chunk of code that none of the maintainer really understands.

Well maybe you should try?

> You two are probably living in your hi-fi bubble, and dithering and noise shaping are an important thing to you. But I have never heard of it before, I've never used an audio player which had a setting with this name, and I honestly didn't miss it.

There's no need to try to be offensive. Just because media software doesn't expose it as an option doesn't mean it doesn't happen. Google it. I'm sure you can find references to it in ffmpeg and I know for a fact that gstreamer does it. Just because you don't know what it is doesn't mean it's not common and useful.

> The only one of the backends that would support it out of the box would be gstreamer, wouldn't it?

 No. Look at the code. It is backend independent.

2021-05-19 07:34 UTC, JasonLG1979 commented
> It doesn't change that it's a huge chunk of code that none of the maintainer really understands.

Well maybe you should try?

> You two are probably living in your hi-fi bubble, and dithering and noise shaping are an important thing to you. But I have never heard of it before, I've never used an audio player which had a setting with this name, and I honestly didn't miss it.

There's no need to try to be offensive. Just because media software doesn't expose it as an option doesn't mean it doesn't happen. Google it. I'm sure you can find references to it in ffmpeg and I know for a fact that gstreamer does it. Just because you don't know what it is doesn't mean it's not common and useful.

> The only one of the backends that would support it out of the box would be gstreamer, wouldn't it?

No. Look at the code. It is backend independent.

> It just doesn't mean anything to "ordinary" people. I'd just be glad to deliver the audio as close as possible to the original, maybe even bit perfect, and if someone isn't satisfied, they could do whatever they want with it, but just after librespot.

You're not going to get "bit perfect" lossy audio. That's not how lossy audio works. Lossy audio does not have a bit depth. That's one of the reasons to dithering and noise shape. In turning the audio back to PCM it has to be requantized to have a bit depth again. That causes errors. None of this is controversial, magical or even fancy. It's how it's done.

> It just doesn't mean anything to "ordinary" people. I'd just be glad to deliver the audio as close as possible to the original, maybe even bit perfect, and if someone isn't satisfied, they could do whatever they want with it, but just after librespot.

> And believe it or believe it not, but outside of your bubble no one would hear a difference.

The devices that stand to gain the most are actually DACs that only do 16 bit (basically cheap $5 dongles) 24 and 32 bit DAC really don't need it because the digital noise floor is well below the physical noise floor of the DAC so quantization noise is masked.

> That is why I'm not really convinced that the change is worth the additional code complexity, the close integration into every single backend and all the configuration option that most users won't understand are worth it.

Maybe actually do some research on the subject and not rely on your preconceived, uninformed biases?

2021-05-19 09:53 UTC, roderickvd commented
@Johannesd3 I too am sorry to say that when you portray me or anyone else as "living in a bubble", and make generalizations on what that might or might not mean, that strikes me as presumptuous and demeaning. But I am sure that you mean well. So I ask to continue discussion on technical merits.

Dithering is not an opinion but a well-documented, widely implemented and academically supported trait of digital audio.  [Wikipedia](https://en.wikipedia.org/wiki/Dither#Usage) offers an easy to understand explanation. What *is* subject to opinion, is whether you want it in `librespot` or not. So on to address your technical points.

Looking back when I introduced high quality audio formats, I made the mistake of not introducing a `struct Requantizer` then but leaving `convert::to_s16(samples)` et al dangling in `convert` module scope. If I had made it to be `requantizer.to_s16(samples)` we might have less of a discussion over close integration, over which we differ in opinion. The call out to `to_s16(samples)` is already there and this is the same entry point. The one difference being that we now need to pass a `&mut requantizer` to keep state whereas the current implementation is static. As I see it, the integration isn't any closer.

Thinking about it now maybe I should make it to be `requantizer.to_s16(samples)` instead of `convert::to_s16(samples, requantizer)`, I think it's a much nicer abstraction. I'll play around with it after work.

Conversely while I think your `sinky` approach truly is a clever processing chain, accessing a `Sink` and getting back a `Sink` again, I think that's adding more weight than just having the entry point to `requantizer.to_s16(samples)`. There's no need to have a chain when a) we can do everything we want in the requantizer and b) there's a required ordering of things (dithering is not an effect you can insert into any position in a chain, it's an operation in the final stage of reformatting from float to integer).

I can be pragmatic about it and say, yeah let's go that route if you and @sashahilton00 would then sign-off on this. But again I think that's moving in the opposite direction. I am genuinely curious why you think a chain of filters is simpler than a single call to a requantizer.

Finally, the default settings are such that they are sane and safe for all users without tweaking options. And for advanced users, well, choice is good.

2021-05-19 15:01 UTC, Johannesd3 commented
> I too am sorry to say that when you portray me or anyone else as "living in a bubble", and make generalizations on what that might or might not mean, that strikes me as presumptuous and demeaning. But I am sure that you mean well.

Maybe my words were too harsh, I'm sorry. What I was trying to say: You and @JasonLG1979 have simply different interests and different priorities than most people involved here. Such features don't seem very important or urgent to me, but they are to you.

> let's go that route if you and @sashahilton00 would then sign-off on this

Please don't respect me as authority here, I'm contributing to this project hardly longer than you. Yes, I have this "Member" badge, but I didn't ask for it, and I will only use it for some small things. The decisions are completely up to @sashahilton00.

> What is subject to opinion, is whether you want it in librespot or not. 

As you maybe noticed, I like to focus on the technical details. My contributions consist of updating dependencies, cleaning up the public api, fixing new clippy warnings, trying to improve code quality, thinking about design questions, and so on. I don't know why I like to do this. I don't even use librespot in real life. But when I first came in touch with librespot, it seemed that no one paid much attention to these things, so I tried to help.

Please try to understand my point of view: I'm trying slowly to clean up, simplify, reorganize a bit (at least I hope it is perceived this way), but your PRs add lots of new complexity for features I never knew I wanted them. If this features make sense or not is a totally different question, but you're working automatically "against" me. 

> I am genuinely curious why you think a chain of filters is simpler than a single call to a requantizer.

It is not immediately simpler. I hope that it's easier to reason about it if one knows that all audio processing takes place in a certain way, and doesn't have to search for all modifications across different files, "volume here, normalization there, and dithering in the backends, and hmm, was it really everything"? With a design similarly to the suggested, you would have one place where all these filters are listed (in this case the implemention of  `SinkBuilder` if I remember correctly). 

But I know that it adds some other kind of complexity. It's a trade-off, and I'm not sure whether it's worth it just from this point of view.

However, there's another thing: This "chain of filters" approach has the advantage that it can live on its own, in a separate crate, even in a separate repository.

@sashahilton00: Just suppose @roderickvd maintains a cross-platform audio crate. It could be based on librespot's current `backend` module, or maybe be a complete rewrite. Could you imagine to replace the current multi-backend mess by this single crate?

@roderickvd No need to wait for PR reviews, you could give free rein to your skills. All dithering, noise shaping, converting, resampling, etc. could be implemented over there. With all your enthusiasm, I'm pretty sure it will be great. But thanks to the "sinky" design, it would be possible to specify in librespot how the filter chain looks like, by just adding or removing a few lines. This would be my dream solution.

2021-05-19 17:07 UTC, JasonLG1979 commented
> Maybe my words were too harsh, I'm sorry.

Ya think? 

> What I was trying to say: You and @JasonLG1979 have simply different interests and different priorities than most people involved here. Such features don't seem very important or urgent to me, but they are to you.

Code structure and organization is of very little concern to me beyond an academic curiosity. That's for the maintainers to decide, I really don't care that much. But this is one of those "quality of life" features that users didn't know they wanted or needed until they get it. It benefits everyone who actually uses librespot in it's current form today. Denying this in the name of some mythical future version of librespot that doesn't exist is a mistake and a form of preemptive premature optimization IMHO.  This is a matter of fixing what we have today. Not doing this was a bug in the 1st place. This is a bug fix just as much as it's a feature.

My only complaints from a user perspective are listed in the cons section of my above comment.

2021-05-19 17:21 UTC, JasonLG1979 commented
> It is not immediately simpler. I hope that it's easier to reason about it if one knows that all audio processing takes place in a certain way, and doesn't have to search for all modifications across different files, "volume here, normalization there, and dithering in the backends, and hmm, was it really everything"? With a design similarly to the suggested, you would have one place where all these filters are listed (in this case the implemention of SinkBuilder if I remember correctly).

> But I know that it adds some other kind of complexity. It's a trade-off, and I'm not sure whether it's worth it just from this point of view.

> However, there's another thing: This "chain of filters" approach has the advantage that it can live on its own, in a separate crate, even in a separate repository.

> @sashahilton00: Just suppose @roderickvd maintains a cross-platform audio crate. It could be based on librespot's current backend module, or maybe be a complete rewrite. Could you imagine to replace the current multi-backend mess by this single crate?

> @roderickvd No need to wait for PR reviews, you could give free rein to your skills. All dithering, noise shaping, converting, resampling, etc. could be implemented over there. With all your enthusiasm, I'm pretty sure it will be great. But thanks to the "sinky" design, it would be possible to specify in librespot how the filter chain looks like, by just adding or removing a few lines. This would be my dream solution.

> Edit: And of course, everyone else could write audio players that make use of your work, it wouldn't be restricted to this application.

In my mind this about creating a default reference player. There's no need to complicate things with an effects chain. Realistically if a user of libresopt wanted to do their own audio processing they could just use librespot minus playback as a lib and use an existing audio framework or write their own player that suits their needs. Over complicating things in the name of making things less complicated seems counter to your stated goals.

2021-05-19 17:56 UTC, roderickvd commented
> Maybe my words were too harsh, I'm sorry. What I was trying to say: You and @JasonLG1979 have simply different interests and different priorities than most people involved here. Such features don't seem very important or urgent to me, but they are to you.

Thanks, I appreciate your response.
 
> I don't even use librespot in real life. But when I first came in touch with librespot, it seemed that no one paid much attention to these things, so I tried to help. [...] I don't know why I like to do this. 

Oh wow 😆

> As you maybe noticed, I like to focus on the technical details. My contributions consist of updating dependencies, cleaning up the public api, fixing new clippy warnings, trying to improve code quality, thinking about design questions, and so on. 

Well like you say I don't know *where* you're getting you're energy from, but I'm hoping you and the rest will join me (and set me up) in implementing the new capabilities API and CDN. May I?

As we're being courteous, it's obvious you are very good at Rust.

> Please try to understand my point of view: I'm trying slowly to clean up, simplify, reorganize a bit (at least I hope it is perceived this way), but your PRs add lots of new complexity for features I never knew I wanted them. If this features make sense or not is a totally different question, but you're working automatically "against" me.

Good to share that insight, I can see how that might come across. Here's my honest take on it. I'm real glad every time I see you're doing code improvement and particularly when it improves decoupling or the `librespot` API. I'm glad exactly because it paves the way for doing new and exciting stuff.

So here's to hoping we all see this as complementary rather than contrary.

> > I am genuinely curious why you think a chain of filters is simpler than a single call to a requantizer.
> 
> It is not immediately simpler. I hope that it's easier to reason about it if one knows that all audio processing takes place in a certain way, and doesn't have to search for all modifications across different files, "volume here, normalization there, and dithering in the backends, and hmm, was it really everything"? With a design similarly to the suggested, you would have one place where all these filters are listed (in this case the implemention of `SinkBuilder` if I remember correctly).
> 
> But I know that it adds some other kind of complexity. It's a trade-off, and I'm not sure whether it's worth it just from this point of view.

I'm with @JasonLG1979 here. There's no need for an effects chain because *that* certainly would not be within `librespot` scope. So this is really it: volume control, normalisation, dithering, noise shaping. Nothing more. And in that order.

Again I'll try and push the `requantizer.to_s16(samples)` idea later tonight and I think that's as clean and simple as it gets.

If you really wanted to have everything centred around some single piece then you could think of a `PlaybackConfig` struct that takes the volume control, normalisation method, and so on, which you would then have to pass around. I think that would unnecessarily increase coupling.

> However, there's another thing: This "chain of filters" approach has the advantage that it can live on its own, in a separate crate, even in a separate repository.

With my work in #685 it already is (just not in a separate repository). Everything would be contained to the `playback` crate.

> @roderickvd No need to wait for PR reviews, you could give free rein to your skills. All dithering, noise shaping, converting, resampling, etc. could be implemented over there. With all your enthusiasm, I'm pretty sure it will be great. 

While I appreciate the compliments, it's not the reviews that I mind. In fact I think they improve quality. I'm certainly triggered by suggestions given by you, @sashahilton00 and @ashthespy on various accounts. It would however be helpful and motivating if PR's would be handled faster. That would also help with your earlier point, where you feel you're cleaning up and someone else submits another and diverging feature.

Of course I respect everyone's agenda, but since we're speaking freely, that'd be one of my wishes.

2021-05-19 18:28 UTC, Johannesd3 commented
If you find the "sinky" approach too complicated – I can understand it. Nevertheless, I think a crate of this kind is really missing in the rust ecosystem. The api could be simpler of course, without requiring some kind of chain.

Look, librespot attracts different interests, and that's hard to manage in such a small project. If librespot would not have to care for perfect audio output because others do, it would be relief for the current maintainers.

And (because I learned today that missing dithering is a bug) it could potentially help many other Rust projects fixing its bugs.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________
From: Roderick van Domburg ***@***.***>
Sent: Wednesday, May 19, 2021 7:57:19 PM
To: librespot-org/librespot ***@***.***>
Cc: Johannesd3 ***@***.***>; Comment ***@***.***>
Subject: Re: [librespot-org/librespot] Implement dithering and noise shaping (#694)


Maybe my words were too harsh, I'm sorry. What I was trying to say: You and @JasonLG1979<https://github.com/JasonLG1979> have simply different interests and different priorities than most people involved here. Such features don't seem very important or urgent to me, but they are to you.

Thanks, I appreciate your response.

I don't even use librespot in real life. But when I first came in touch with librespot, it seemed that no one paid much attention to these things, so I tried to help. [...] I don't know why I like to do this.

Oh wow 😆

As you maybe noticed, I like to focus on the technical details. My contributions consist of updating dependencies, cleaning up the public api, fixing new clippy warnings, trying to improve code quality, thinking about design questions, and so on.

Well like you say I don't know where you're getting you're energy from, but I'm hoping you and the rest will join me (and set me up) in implementing the new capabilities API and CDN. May I?

As we're being courteous, it's obvious you are very good at Rust.

Please try to understand my point of view: I'm trying slowly to clean up, simplify, reorganize a bit (at least I hope it is perceived this way), but your PRs add lots of new complexity for features I never knew I wanted them. If this features make sense or not is a totally different question, but you're working automatically "against" me.

Good to share that insight, I can see how that might come across. Here's my honest take on it. I'm real glad every time I see you're doing code improvement and particularly when it improves decoupling or the librespot API. I'm glad exactly because it paves the way for doing new and exciting stuff.

So here's to hoping we all see this as complementary rather than contrary.

I am genuinely curious why you think a chain of filters is simpler than a single call to a requantizer.

It is not immediately simpler. I hope that it's easier to reason about it if one knows that all audio processing takes place in a certain way, and doesn't have to search for all modifications across different files, "volume here, normalization there, and dithering in the backends, and hmm, was it really everything"? With a design similarly to the suggested, you would have one place where all these filters are listed (in this case the implemention of SinkBuilder if I remember correctly).

But I know that it adds some other kind of complexity. It's a trade-off, and I'm not sure whether it's worth it just from this point of view.

I'm with @JasonLG1979<https://github.com/JasonLG1979> here. There's no need for an effects chain because that certainly would not be within librespot scope. So this is really it: volume control, normalisation, dithering, noise shaping. Nothing more. And in that order.

Again I'll try and push the requantizer.to_s16(samples) idea later tonight and I think that's as clean and simple as it gets.

If you really wanted to have everything centred around some single piece then you could think of a PlaybackConfig struct that takes the volume control, normalisation method, and so on, which you would then have to pass around. I think that would unnecessarily increase coupling.

However, there's another thing: This "chain of filters" approach has the advantage that it can live on its own, in a separate crate, even in a separate repository.

With my work in #685<https://github.com/librespot-org/librespot/pull/685> it already is (just not in a separate repository). Everything would be contained to the playback crate.

@roderickvd<https://github.com/roderickvd> No need to wait for PR reviews, you could give free rein to your skills. All dithering, noise shaping, converting, resampling, etc. could be implemented over there. With all your enthusiasm, I'm pretty sure it will be great.

While I appreciate the compliments, it's not the reviews that I mind. In fact I think they improve quality. I'm certainly triggered by suggestions given by you, @sashahilton00<https://github.com/sashahilton00> and @ashthespy<https://github.com/ashthespy> on various accounts. It would however be helpful and motivating if PR's would be handled faster. That would also help with your earlier point, where you feel you're cleaning up and someone else submits another and diverging feature.

Of course I respect everyone's agenda, but since we're speaking freely, that'd be one of my wishes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/librespot-org/librespot/pull/694#issuecomment-844336984>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMMMGGKFQYDY3XVPI7WOJT3TOP3X7ANCNFSM424C5YIA>.

2021-05-19 19:42 UTC, roderickvd commented
Let f7bcb49 be the positive outcome of this discussion here. Wrapping up the requantizer into the converter, resulting in a single call such as `&converter.f32_to_s16(samples)` is as clear as it gets I think!

> If you find the "sinky" approach too complicated – I can understand it. Nevertheless, I think a crate of this kind is really missing in the rust ecosystem. The api could be simpler of course, without requiring some kind of chain. Look, librespot attracts different interests, and that's hard to manage in such a small project.

I don't oppose taking maintainership over such a solution, but my wish for faster PR rotation is not isolated to just the `playback` crate.

2021-05-19 21:10 UTC, JasonLG1979 commented
> I don't oppose taking maintainership over such a solution, but my wish for faster PR rotation is not isolated to just the `playback` crate.

I have experienced this and it sucks to basically be kept in a holding pattern because you want to do a few different things but you don't want to deal with 30 concurrent PR's. It really kills your momentum.

2021-05-21 00:33 UTC, JasonLG1979 commented
@roderickvd everything seems to work as expected. Pretty much exactly the same as the last time I tested.

2021-05-21 08:55 UTC, roderickvd commented
> The defaults seem sensible, which is the most important part but with so many different combos of dithering and noise shaping and considering that in my testing even the most computationally heavy setting will run on a Pi Zero no problem, I wonder if logical combos can't be a little more abstracted out basically something like just a setting for delta-sigma DACs (which seems to already be the default) and a setting or settings specifically for NOS/R2R/multi-bit Dacs?

What would you propose? Maybe you can draft some command line options?

Here's my thought process on a couple of points.

First, I can see how the command line options can seem daunting and meaningless to many users. We've mapped it to sane defaults and proposed wiki documentation. That largely mitigates the issue but could we do better?

With regards to the dithering, we could cut down options and remove the `rect` (RPDF) and `sto` options. `tri` (TPDF) and `hp` (high-passed TPDF) are the theoretical optimal ones. `tri` is the one anyone would normally want to use when also using noise shaping, `hp` without noise shaping. I thew in `gauss` to boot for a more analog sound. It's debatable to keep that one around, however, I like to provide options for those that try to approach vinyl (often the same crowd that is interested in NOS).

Re-reading the above paragraph, you could map those to more meaningful terms, e.g. call something `analog` (not very precise, but anyway) to use `gauss` or otherwise pick `tri` or `hp` depending on whether noise shaping is configured yes or no.

Second, noise shaping (the FIR ones, not `fract`). I find this harder to map to just an oversampling knob, because it's very much a matter of preference, trading off absolute noise and perceived noise as well as CPU usage.

N.B. to be precise it's not really _oversampling_ that matters down the line in the DAC, but whether that DAC does noise shaping itself. Many oversampling DACs shape noise but not all of them, and in some it is configurable. So oversampling and noise shaping seem related but are not the same.

Third, the special case of `fract` noise shaping which can be seen as a substitute for dithering on power-constrained hardware (think batteries, not CPU). Maybe a knob like `powersave`.

If you could put some thought into it and propose alternative command line options?

Depending on the outcome we could decide on the current options (more advanced, more user control) or proposed options (dumbed-down, more user friendly).

2021-05-21 13:21 UTC, JasonLG1979 commented
> What would you propose? Maybe you can draft some command line options?

See I don't know? I guess maybe get rid of some of the intermediate options. Having just `none`, `tri` and `hp` would be a good start on dithering I haven't tried out `gauss`. I'll take your word for it on the "analog" part,lol!!!

Noise shaping is much the same, maybe cut out some of the intermediate options So maybe just `none`, `fract`, `iew9`, `fw24`?

The above are just examples. You obviously know more about it than I do. Basically my complaint is that although choice is good to many choices without a clear difference is not. It's like offering 15 different types of vanilla ice cream,lol!!!

2021-05-21 13:33 UTC, JasonLG1979 commented
> Depending on the outcome we could decide on the current options (more advanced, more user control) or proposed options (dumbed-down, more user friendly).

I think if the number of different options were trimmed (and therefore the number of combinations) along with a your reasonable defaults and some documentation in the wiki should be enough.

2021-05-21 14:33 UTC, JasonLG1979 commented
My next question is more of a curiosity. I see you chose the "DC DAC Modeled" method for converting from float to int. I'm wondering why you picked this method? In a [follow up](http://blog.bjornroche.com/2009/12/linearity-and-dynamic-range-in-int.html) post by the same author he seems to say that that isn't necessarily the best method. He seems to suggest that method 4 is better (`float>0?float*0x7FFF:float*0x8000`).

He says:

> All that said, there is no reason not to develop software, especially libraries, drivers and other software intended for use by multiple type of users including audiophiles and pro audio engineers, that is convenient to use while meeting the highest audio standards: just use the asymmetric converters.

2021-05-21 20:20 UTC, roderickvd commented
> My next question is more of a curiosity. I see you chose the "DC DAC Modeled" method for converting from float to int. I'm wondering why you picked this method? In a [follow up](http://blog.bjornroche.com/2009/12/linearity-and-dynamic-range-in-int.html) post by the same author he seems to say that that isn't necessarily the best method. He seems to suggest that method 4 is better (`float>0?float*0x7FFF:float*0x8000`).

This is not new to this PR but was introduced in #660. Regardless I'm glad you asked.

This follow-up post you mention is [debated](https://lists.apple.com/archives/coreaudio-api/2009/Dec/msg00118.html). And I agree with the critique that treating negative and positive values differently produces non-linearities. Method 0 solves this at the not-so-important cost of introducing some DC bias, regardless of another point of debate which is whether +1.0 is considered clipping or not.

Now why I'm glad you asked, is that your question led me to some further investigations testing my own beliefs.

An important point in the critique is "Other ranges would be equally valid so long as every process involved is aware of the standard." and this matches Bjorn's statement that "In the dynamic analysis, it becomes clear that using different scaling factors produces more noise whether dither is used or not. In fact, the difference made by dither is dwarfed by the difference in techniques."

As I'd explain it: it's important to pick the best method, but it's more important to use the same method throughout the chain. Now for the first time ever I opened the reference Vorbis encoder and guess what, it's using Method 1: https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L2074-L2076

And so testing my own beliefs, yes I will be adjusting the conversion but to method 1 rather than 4. Thanks for the prod!

2021-05-21 20:30 UTC, JasonLG1979 commented
Thank you for the explanation.



> As I'd explain it: it's important to pick the best method, but it's more important to use the same method throughout the chain. Now for the first time ever I opened the reference Vorbis encoder and guess what, it's using Method 1: https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L2074-L2076
> 
> And so testing my own beliefs, yes I will be adjusting the conversion but to method 1 rather than 4. Thanks for the prod!

That was going to be my 2nd question. If there's a good idea what the "in" method was,lol!!!

2021-05-21 21:36 UTC, roderickvd commented
> Edit: Or is that just the ref "out" method?

Yes the original link was to the decoder. The encoder just takes `[-1.0..=1.0]` normalised samples, it's not set in stone how to arrive at that. The example encoder also uses method 1 though, just like the decoder, so it's safe to say that's what's assumed: https://github.com/xiph/vorbis/blob/master/examples/encoder_example.c#L196-L202

I pushed a fix in 68f409c. It's somewhat stray in the scope of this PR, but is easy to extract if necessary.

2021-05-21 22:15 UTC, JasonLG1979 commented
Right on. Now I'm curious to see if there's even an audible difference,lol!!! But being technically correct is always good though none the less even if it's not audible.

2021-05-22 07:01 UTC, JasonLG1979 commented
@roderickvd  "Method 1" seems to sound at least as good or better than "Method 0" on my Pi Zero with a HIFIBERRY DAC+ ZERO DAC HAT. Not that anyone could realistically tell the difference on a $15 slave DAC with a SNR in the low 90's dB. I'm about 99.999% sure it's confirmation bias. I'll test it out on my (much better but still cheap) JDS Labs OLDAC tomorrow but I expect about the same amount of bias and certainty,lol!!!

2021-05-22 09:36 UTC, roderickvd commented
Same here even though my DAC has a SNR of 129 dB. It’s measurable but likely not directly audible. There is excellent evidence however that reduced harmonic distortion does reduce listening fatigue en improves perception unconsciously. 

Back to the topic of command line options, I’ll come up with some alternatives later and hopefully move to final decision stage on this one.

2021-05-22 19:40 UTC, JasonLG1979 commented
> Same here even though my DAC has a SNR of 129 dB. It’s measurable but likely not directly audible. There is excellent evidence however that reduced harmonic distortion does reduce listening fatigue en improves perception unconsciously.

The guy to ask might be Amir at Audio Science Review. He has the test equipment to verify how much of an objective difference there really is. Not that he has the time or would even care,lol!!!

> Back to the topic of command line options, I’ll come up with some alternatives later and hopefully move to final decision stage on this one.

Right on. I look forward to testing out whatever you come up with.

2021-05-23 20:31 UTC, roderickvd commented
Working on this I came to my senses as I saw the huge number of cases I was trying to cater to. Instead of coming up with some extensive mapping, I really cut down the number of features 35296bf.

For starters, I took out the entire `NoiseShaper` module and two of the `Ditherer` types. Please read the commit message for more details.

What do you think now it's trimmed? All it needs now is Wiki documentation on `--dither {none|gpdf|tpdf|tpdf_hp}` while users that don't care or don't know are set up with the sane and safe `tpdf` by default.

2021-05-23 21:13 UTC, JasonLG1979 commented
> Working on this I came to my senses as I saw the huge number of cases I was trying to cater to. Instead of coming up with some extensive mapping, I really cut down the number of features [35296bf](https://github.com/librespot-org/librespot/commit/35296bfb428012404264eb6d09fa67ed6689880c).
> 
> For starters, I took out the entire `NoiseShaper` module and two of the `Ditherer` types. Please read the commit message for more details.
> 
> What do you think now it's trimmed? All it needs now is Wiki documentation on `--dither {none|gpdf|tpdf|tpdf_hp}` while users that don't care or don't know are set up with the sane and safe `tpdf` by default.

That makes a lot more sense to me. Choice is good but to many complicated choices not so much. I like this much better.

2021-05-23 21:18 UTC, JasonLG1979 commented
It might not be a bad idea to make a note that if your DAC supports S32 (I'm not aware of any DACs that support F32?) a user should use set librespot to S32. In any event the highest supported format should always be used. That may be counter-intuitive to people who are unfamiliar with how lossy audio works and that want "bit-perfect" audio. They may assume S16 is the best format to use since the file before conversion was more than likely 16 bit to begin with.

2021-05-23 21:23 UTC, roderickvd commented
We can add it to the wiki.

2021-05-23 21:35 UTC, JasonLG1979 commented
@roderickvd Can there be a 0.2.1(?) release with among other things this and the volume fix. I think it would be a pretty solid release to tide people over until the new API is figured out.

2021-05-23 21:40 UTC, Johannesd3 reviewed
Last time I looked at it, it was much more confusing :)

2021-05-23 21:40 UTC, Johannesd3 commented on playback/src/dither.rs
> +    pub fn default() -> fn() -> Box<Self> {
Using `default` for a function other than `-> Self` is confusing.

2021-05-23 21:41 UTC, Johannesd3 commented
Would be `0.3.0`, it's all breaking.

2021-05-23 21:45 UTC, JasonLG1979 commented
> Would be `0.3.0`, it's all breaking.

There would be new args but but nothing would break if a user used the same args from 0.2 that I'm aware of?

2021-05-23 21:46 UTC, Johannesd3 commented
It would/could break other applications depending on librespot as library.

2021-05-23 21:49 UTC, JasonLG1979 commented
> It would/could break other applications depending on librespot as library.

True. Whatever then make it 0.3? I guess I may be enthusiastic for the improvements but I'd like to see this out the door because I think it adds a lot of value. I'd hate to see this sit on the back burner until after the new API was figured out. I think a lot of people would really like to see (or rather hear) these changes.

2021-05-23 21:57 UTC, sashahilton00 commented
This can be merged into dev whenever, the api for librespot is unstable anyway, we just try to stick with bumping the minor on breaking changes, and the patch on features/fixes atm.

2021-05-23 22:08 UTC, JasonLG1979 commented
> This can be merged into dev whenever, the api for librespot is unstable anyway, we just try to stick with bumping the minor on breaking changes, and the patch on features/fixes atm.

Bummer. I was hoping for a release so things like raspotify and the various streamer distros like Moode and Volumio would pick it up. Like I said I really think it would be a good stop gap until the new API is completely figured out. It really represents a leap forward as far as having a "reference quality" player in librespot (well as "reference quality" as you can get for a lossy format). Having it in the wild now would also help shake out any potential bugs earlier before the new API goes stable.

2021-05-23 22:12 UTC, sashahilton00 commented
> Bummer. I was hoping for a release so things like raspotify and the various streamer distros like Moode and Volumio would pick it up. Like I said I really think it would be a good stop gap until the new API is completely figured out. It really represents a leap forward as far as having a "reference quality" player in librespot (well as "reference quality" as you can get for a lossy format). Having it in the wild now would also help shake out any potential bugs earlier before the new API goes stable. 

There's nothing to say that the gap between `0.2.0` and `0.3.0` has to be any great length of time, it just ended up that way for the last release. If we end up bumping the minor 3 times in a week then so be it, shouldn't make any difference to people using librespot, they can just pin versions as necessary.

2021-05-23 22:16 UTC, JasonLG1979 commented
> There's nothing to say that the gap between `0.2.0` and `0.3.0` has to be any great length of time, it just ended up that way for the last release. If we end up bumping the minor 3 times in a week then so be it, shouldn't make any difference to people using librespot, they can just pin versions as necessary.

Good to hear. I guess I just misunderstood what you said. For projects that use librespot as a monolithic binary 0.3.x with this included over 2.0.0 would be a no-brainer.

2021-05-23 22:23 UTC, roderickvd commented
#745 alone warrants a `0.2.1` release exactly because it is upsetting to other applications that use this as a library.

I'll push a change for @Johannesd3 review shortly, if there are any other comments, please get them (or send a thumbs up) so I can do a final sweep.

2021-05-26 19:07 UTC, Johannesd3 commented
This failure is ok, happens once a while

2021-05-26 19:08 UTC, roderickvd commented
Yeah I'll merge if the others pass.

2021-05-26 19:19 UTC, merged